import { z } from "zod";

import {
  isValidAlias,
  isValidCvu,
  normalizeAlias,
  normalizeCvu,
} from "@/features/account/domain/account-identifiers";
import { parseAmount } from "@/shared/lib/money";
import {
  validationDetails,
  type ValidationDetails,
} from "@/shared/lib/validation";

/**
 * Transfer validation shared by the send form (instant feedback) and the server (source of
 * truth). Messages are UI copy, so they are in Spanish.
 */
export const TRANSFER_MESSAGES = {
  bodyNotObject:
    "Enviá un objeto JSON con destinatario, monto y clave de idempotencia",
  recipientRequired: "Ingresá el alias o CVU de destino",
  cvuLength: "El CVU tiene 22 dígitos",
  cvuInvalid: "Revisá el CVU: algún dígito no es correcto",
  aliasInvalid:
    "El alias tiene entre 6 y 20 caracteres: letras, números, puntos o guiones",
  amountInvalid: "Ingresá un monto válido, con hasta 2 decimales",
  amountPositive: "El monto tiene que ser mayor a cero",
  amountTooLarge: "El monto máximo por transferencia es $100,000",
  descriptionInvalid: "El motivo tiene que ser un texto",
  descriptionTooLong: "El motivo puede tener hasta 60 caracteres",
  cardInvalid: "Elegí una tarjeta válida",
  idempotencyKeyInvalid:
    "Falta la clave de idempotencia (un UUID por intento de transferencia)",
} as const;

/** Per-transfer cap: US$ 100,000.00. A sanity limit, well inside `Decimal(12,2)`. */
export const MAX_TRANSFER_CENTS = 100_000_00;
export const DESCRIPTION_MAX_LENGTH = 60;

/** How the sender identifies the recipient: a CVU (22 digits) or an alias. */
export type RecipientKey =
  { kind: "alias"; alias: string } | { kind: "cvu"; cvu: string };

const recipientSchema = z
  .string({ error: TRANSFER_MESSAGES.recipientRequired })
  .trim()
  .min(1, TRANSFER_MESSAGES.recipientRequired)
  .max(64, TRANSFER_MESSAGES.aliasInvalid)
  .transform((raw, ctx): RecipientKey => {
    const digits = normalizeCvu(raw);
    // Only digits (once spaces and dashes are gone) means the user typed a CVU.
    if (/^\d+$/.test(digits)) {
      if (digits.length !== 22) {
        ctx.issues.push({
          code: "custom",
          message: TRANSFER_MESSAGES.cvuLength,
          input: raw,
        });
        return z.NEVER;
      }
      if (!isValidCvu(digits)) {
        ctx.issues.push({
          code: "custom",
          message: TRANSFER_MESSAGES.cvuInvalid,
          input: raw,
        });
        return z.NEVER;
      }
      return { kind: "cvu", cvu: digits };
    }
    const alias = normalizeAlias(raw);
    if (!isValidAlias(alias)) {
      ctx.issues.push({
        code: "custom",
        message: TRANSFER_MESSAGES.aliasInvalid,
        input: raw,
      });
      return z.NEVER;
    }
    return { kind: "alias", alias };
  });

const amountSchema = z
  .union([z.string(), z.number()], { error: TRANSFER_MESSAGES.amountInvalid })
  .transform((raw, ctx) => {
    const parsed = parseAmount(raw);
    const message = !parsed
      ? TRANSFER_MESSAGES.amountInvalid
      : parsed.cents === 0
        ? TRANSFER_MESSAGES.amountPositive
        : parsed.cents > MAX_TRANSFER_CENTS
          ? TRANSFER_MESSAGES.amountTooLarge
          : null;
    if (!parsed || message) {
      ctx.issues.push({ code: "custom", message: message ?? "", input: raw });
      return z.NEVER;
    }
    return parsed;
  });

const transferRequestSchema = z
  .object(
    {
      recipient: recipientSchema,
      amount: amountSchema,
      description: z
        .string({ error: TRANSFER_MESSAGES.descriptionInvalid })
        .trim()
        .max(DESCRIPTION_MAX_LENGTH, TRANSFER_MESSAGES.descriptionTooLong)
        .nullish()
        .transform((value) => value || undefined),
      // Optional: the sender's primary card when absent.
      cardId: z
        .string({ error: TRANSFER_MESSAGES.cardInvalid })
        .trim()
        .min(1, TRANSFER_MESSAGES.cardInvalid)
        .max(64, TRANSFER_MESSAGES.cardInvalid)
        .optional(),
      // One per transfer attempt, generated by the client and reused on retries.
      idempotencyKey: z
        .string({ error: TRANSFER_MESSAGES.idempotencyKeyInvalid })
        .trim()
        .toLowerCase()
        .pipe(z.uuid({ error: TRANSFER_MESSAGES.idempotencyKeyInvalid })),
    },
    { error: TRANSFER_MESSAGES.bodyNotObject },
  )
  .transform(({ amount, ...rest }) => ({
    ...rest,
    amount: amount.amount,
    amountCents: amount.cents,
  }));

export type TransferRequest = z.output<typeof transferRequestSchema>;

type Parsed<T> =
  { success: true; data: T } | { success: false; details: ValidationDetails };

export function parseTransferRequest(input: unknown): Parsed<TransferRequest> {
  const result = transferRequestSchema.safeParse(input);
  return result.success
    ? { success: true, data: result.data }
    : { success: false, details: validationDetails(result.error) };
}

/** One amount as typed in the send form ("12,30" or "12.30"), with the same rules. */
export function parseTransferAmount(
  raw: string,
): { success: true; cents: number } | { success: false; message: string } {
  const result = amountSchema.safeParse(raw);
  return result.success
    ? { success: true, cents: result.data.cents }
    : {
        success: false,
        message:
          result.error.issues[0]?.message ?? TRANSFER_MESSAGES.amountInvalid,
      };
}

const recipientQuerySchema = z.object({ q: recipientSchema });

/** `?q=` of the recipient preview (confirm step): an alias or a CVU. */
export function parseRecipientQuery(q: string | null): Parsed<RecipientKey> {
  const result = recipientQuerySchema.safeParse({ q: q ?? undefined });
  return result.success
    ? { success: true, data: result.data.q }
    : { success: false, details: validationDetails(result.error) };
}
