import { z } from "zod";

import {
  validationDetails,
  type ValidationDetails,
} from "@/shared/lib/validation";

import {
  DESCRIPTION_MAX_LENGTH,
  TRANSFER_MESSAGES,
  checkTransferAmount,
  checkTransferRecipient,
  type RecipientKey,
} from "./transfer-rules";

export {
  DESCRIPTION_MAX_LENGTH,
  MAX_TRANSFER_CENTS,
  TRANSFER_MESSAGES,
  type RecipientKey,
} from "./transfer-rules";

/**
 * The server's transfer validation (source of truth). Field rules come from
 * `transfer-rules.ts`, the same functions the send form runs while typing, so both give the
 * same verdict; this schema adds the request shape and turns failures into field errors.
 */

const recipientSchema = z
  .string({ error: TRANSFER_MESSAGES.recipientRequired })
  .transform((raw, ctx): RecipientKey => {
    const result = checkTransferRecipient(raw);
    if (!result.ok) {
      ctx.issues.push({ code: "custom", message: result.message, input: raw });
      return z.NEVER;
    }
    return result.key;
  });

/** Canonical amounts only ("1234.56" or a number): the form converts what people type. */
const amountSchema = z
  .union([z.string(), z.number()], { error: TRANSFER_MESSAGES.amountInvalid })
  .transform((raw, ctx) => {
    const result = checkTransferAmount(raw);
    if (!result.ok) {
      ctx.issues.push({ code: "custom", message: result.message, input: raw });
      return z.NEVER;
    }
    return { amount: result.amount, cents: result.cents };
  });

const transferRequestSchema = z
  .object(
    {
      recipient: recipientSchema,
      amount: amountSchema,
      description: z
        .string({ error: TRANSFER_MESSAGES.descriptionInvalid })
        .trim()
        .max(DESCRIPTION_MAX_LENGTH, TRANSFER_MESSAGES.descriptionTooLong)
        .nullish()
        .transform((value) => value || undefined),
      // Optional: the sender's primary card when absent.
      cardId: z
        .string({ error: TRANSFER_MESSAGES.cardInvalid })
        .trim()
        .min(1, TRANSFER_MESSAGES.cardInvalid)
        .max(64, TRANSFER_MESSAGES.cardInvalid)
        .optional(),
      // One per transfer attempt, generated by the client and reused on retries.
      idempotencyKey: z
        .string({ error: TRANSFER_MESSAGES.idempotencyKeyInvalid })
        .trim()
        .toLowerCase()
        .pipe(z.uuid({ error: TRANSFER_MESSAGES.idempotencyKeyInvalid })),
    },
    { error: TRANSFER_MESSAGES.bodyNotObject },
  )
  .transform(({ amount, ...rest }) => ({
    ...rest,
    amount: amount.amount,
    amountCents: amount.cents,
  }));

export type TransferRequest = z.output<typeof transferRequestSchema>;

type Parsed<T> =
  { success: true; data: T } | { success: false; details: ValidationDetails };

export function parseTransferRequest(input: unknown): Parsed<TransferRequest> {
  const result = transferRequestSchema.safeParse(input);
  return result.success
    ? { success: true, data: result.data }
    : { success: false, details: validationDetails(result.error) };
}

const recipientQuerySchema = z.object({ q: recipientSchema });

/** `?q=` of the recipient preview (confirm step): an alias or a CVU. */
export function parseRecipientQuery(q: string | null): Parsed<RecipientKey> {
  const result = recipientQuerySchema.safeParse({ q: q ?? undefined });
  return result.success
    ? { success: true, data: result.data.q }
    : { success: false, details: validationDetails(result.error) };
}
